# Generated by Django 2.2.2 on 2019-06-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HmDesignImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=20)),
                ('design_type', models.CharField(max_length=20)),
                ('dsign_img_link', models.CharField(max_length=2000)),
            ],
        ),
    ]
