# Generated by Django 2.2.2 on 2019-06-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_auto_20190628_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hmdesignimg',
            old_name='dsign_img_link',
            new_name='design_img_link',
        ),
    ]
