# Generated by Django 2.2.2 on 2019-06-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_auto_20190628_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='CstmrFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cst_name', models.CharField(max_length=30)),
                ('cst_feed_msg', models.CharField(max_length=120)),
                ('wrk_at_as', models.CharField(max_length=40)),
            ],
        ),
    ]
