# Generated by Django 2.2.2 on 2019-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_cstmrfeed_cst_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_name', models.CharField(max_length=30)),
                ('mem_about', models.CharField(max_length=120)),
                ('mem_post', models.CharField(max_length=40)),
                ('mem_img', models.CharField(max_length=2000)),
                ('mem_tweet', models.CharField(blank=True, default='https://twitter.com/', max_length=2000)),
                ('mem_facebook', models.CharField(blank=True, default='https://www.facebook.com/', max_length=2000)),
                ('mem_googlep', models.CharField(blank=True, default='https://www.google.com/', max_length=2000)),
                ('mem_insta', models.CharField(blank=True, default='https://www.instagram.com/', max_length=2000)),
            ],
        ),
    ]
