# Generated by Django 2.2.2 on 2019-06-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0007_auto_20190630_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsNLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo_link', models.CharField(default='https://ebaqdesign.com/wp-content/uploads/2018/04/your-logo-registered.png', max_length=2000)),
                ('client_link', models.CharField(default='https://goole.com/', max_length=2000)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
