# Generated by Django 2.2.3 on 2019-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0008_clientsnlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vw_name', models.CharField(max_length=30, verbose_name='Viewer Name')),
                ('vw_email', models.EmailField(max_length=50, verbose_name='Viewer E-Mail')),
                ('vw_subject', models.CharField(max_length=50, verbose_name='Viewer Subject')),
                ('vw_msg', models.TextField(max_length=5000, verbose_name='Viewer Message')),
            ],
            options={
                'verbose_name': 'Viewer Contact Detail',
                'verbose_name_plural': 'Viewer Contact Details',
            },
        ),
    ]
