# Generated by Django 2.2.2 on 2019-07-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0009_blogpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='blg_link',
            new_name='blg_pic',
        ),
    ]
