# Generated by Django 2.2.3 on 2019-07-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0009_contactformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsnlinks',
            name='client_link',
            field=models.CharField(default='https://goole.com/', max_length=2000, verbose_name='Client Link'),
        ),
        migrations.AlterField(
            model_name='clientsnlinks',
            name='client_logo_link',
            field=models.CharField(default='https://ebaqdesign.com/wp-content/uploads/2018/04/your-logo-registered.png', max_length=2000, verbose_name='Client Logo'),
        ),
        migrations.AlterField(
            model_name='cstmrfeed',
            name='cst_feed_msg',
            field=models.CharField(max_length=120, verbose_name='Feedback Message'),
        ),
        migrations.AlterField(
            model_name='cstmrfeed',
            name='cst_img',
            field=models.CharField(max_length=2000, verbose_name='Customer Image'),
        ),
        migrations.AlterField(
            model_name='cstmrfeed',
            name='cst_name',
            field=models.CharField(max_length=30, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='cstmrfeed',
            name='wrk_at_as',
            field=models.CharField(max_length=40, verbose_name='Work At/As'),
        ),
        migrations.AlterField(
            model_name='hmdesignimg',
            name='design_img_link',
            field=models.CharField(max_length=2000, verbose_name='Image Link'),
        ),
        migrations.AlterField(
            model_name='hmdesignimg',
            name='design_name',
            field=models.CharField(max_length=30, verbose_name='Design Name'),
        ),
        migrations.AlterField(
            model_name='hmdesignimg',
            name='design_type',
            field=models.CharField(max_length=20, verbose_name='Design Type(Interior/Exterior)'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='mem_about',
            field=models.CharField(max_length=120, verbose_name='About Member'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='mem_facebook',
            field=models.CharField(blank=True, default='https://www.facebook.com/', max_length=2000, verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='mem_googlep',
            field=models.CharField(blank=True, default='https://www.google.com/', max_length=2000, verbose_name='Google+ Link'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='mem_img',
            field=models.CharField(max_length=2000, verbose_name='Member Image'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='mem_insta',
            field=models.CharField(blank=True, default='https://www.instagram.com/', max_length=2000, verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='mem_name',
            field=models.CharField(max_length=30, verbose_name='Member Name'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='mem_post',
            field=models.CharField(max_length=40, verbose_name='Member Post/Rank'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='mem_tweet',
            field=models.CharField(blank=True, default='https://twitter.com/', max_length=2000, verbose_name='Twitter Link'),
        ),
    ]
