# Generated by Django 2.2.2 on 2019-07-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0010_auto_20190703_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blg_desc',
            field=models.TextField(max_length=10000),
        ),
    ]
