# Generated by Django 2.2.2 on 2019-07-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0011_auto_20190703_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blg_pic',
            field=models.CharField(max_length=2000),
        ),
    ]
