# Generated by Django 2.2.3 on 2019-07-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0012_auto_20190703_1054'),
        ('Content', '0010_auto_20190704_1653'),
    ]

    operations = [
    ]
