# Generated by Django 2.2.3 on 2019-07-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0016_auto_20190708_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contactformmodel',
            options={'verbose_name': 'Visitor  Details', 'verbose_name_plural': 'Visitors Details'},
        ),
        migrations.AlterModelOptions(
            name='cstmrfeed',
            options={'verbose_name': 'Customers Feedback', 'verbose_name_plural': 'Customers Feedback'},
        ),
        migrations.AlterModelOptions(
            name='hmdesignimg',
            options={'verbose_name': 'Home Page Designs Image', 'verbose_name_plural': 'Home Page Design images'},
        ),
        migrations.RenameField(
            model_name='cstmrfeed',
            old_name='cst_feed_msg',
            new_name='cst_feed',
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='vw_email',
            field=models.EmailField(max_length=50, verbose_name="Visitor's E-Mail"),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='vw_msg',
            field=models.TextField(max_length=5000, verbose_name="Visitor's Message"),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='vw_name',
            field=models.CharField(max_length=30, verbose_name="Visitor's Name"),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='vw_subject',
            field=models.CharField(max_length=50, verbose_name="Visitor's Subject"),
        ),
        migrations.AlterField(
            model_name='cstmrfeed',
            name='cst_name',
            field=models.CharField(max_length=30, verbose_name="Customer's Name"),
        ),
    ]
