# Generated by Django 2.2.3 on 2019-07-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0018_auto_20190713_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmdesignimg',
            name='design_type',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=20, verbose_name='Design Type'),
        ),
    ]
