# Generated by Django 2.2.3 on 2019-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0019_auto_20190714_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blg_pic',
            field=models.ImageField(upload_to='', verbose_name='Blog Image'),
        ),
        migrations.AlterField(
            model_name='hmdesignimg',
            name='design_img_link',
            field=models.ImageField(upload_to='', verbose_name='Image Link'),
        ),
        migrations.AlterField(
            model_name='prjimg',
            name='design_img_link',
            field=models.ImageField(upload_to='', verbose_name='Image Link'),
        ),
        migrations.AlterField(
            model_name='prjimg',
            name='design_type',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=20, verbose_name='Design Type'),
        ),
    ]
