# Generated by Django 2.2.3 on 2019-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0020_auto_20190714_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmdesignimg',
            name='design_type',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=10, verbose_name='Design Type'),
        ),
        migrations.AlterField(
            model_name='prjimg',
            name='design_type',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=10, verbose_name='Design Type'),
        ),
    ]
