# Generated by Django 2.2.3 on 2019-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0021_auto_20190714_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmdesignimg',
            name='design_img_link',
            field=models.CharField(max_length=2000, verbose_name='Image Link'),
        ),
    ]
