# Generated by Django 2.2.3 on 2019-07-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0022_auto_20190714_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prjimg',
            name='design_type',
            field=models.CharField(choices=[('Bed Room', 'Bed Room'), ('Drawing Room', 'Drawing Room'), ('Kids Room', 'Kids Room'), ('Ceiling', 'Ceiling'), ('Wardrobe', 'Wardrobe'), ('Kitchen', 'Kitchen'), ('Living Room', 'Living Room')], max_length=10, verbose_name='Design Type'),
        ),
    ]
