# Generated by Django 2.2.3 on 2019-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0028_auto_20190728_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='prjimg',
            name='image',
            field=models.FileField(blank=True, upload_to='admin_photo'),
        ),
        migrations.AlterField(
            model_name='prjimg',
            name='design_img_link',
            field=models.ImageField(upload_to='', verbose_name='Image Link'),
        ),
    ]
