# Generated by Django 2.2.3 on 2019-07-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0029_auto_20190728_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prjimg',
            name='image',
        ),
    ]
